import { nextJsConfig } from "@workspace/eslint-config/next-js"

/** @type {import("eslint").Linter.Config} */
export default [
  // Generated by `msw init`; must not be edited.
  { ignores: ["public/mockServiceWorker.js"] },
  ...nextJsConfig,
]
