/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/data/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_data_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Ready when Postgres and Redis answer.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_data_datasets_get"];
        put?: never;
        /**
         * Upload Dataset
         * @description Multipart upload (`file`, optional `name`), streamed to object storage
         *     while it arrives (app/upload.py).
         */
        post: operations["upload_dataset_api_data_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/datasets/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Sample */
        post: operations["create_sample_api_data_datasets_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_api_data_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        /** Delete Dataset */
        delete: operations["delete_dataset_api_data_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/datasets/{dataset_id}/columns/{column_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Column Type */
        patch: operations["set_column_type_api_data_datasets__dataset_id__columns__column_id__patch"];
        trace?: never;
    };
    "/api/data/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_data_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/datasets/{dataset_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_data_datasets__dataset_id__dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/datasets/{dataset_id}/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_api_data_datasets__dataset_id__query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/datasets/{dataset_id}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rows */
        get: operations["rows_api_data_datasets__dataset_id__rows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/datasets/{dataset_id}/filters/{column}/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filter Values */
        get: operations["filter_values_api_data_datasets__dataset_id__filters__column__values_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/datasets/{dataset_id}/widgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Widgets */
        get: operations["list_widgets_api_data_datasets__dataset_id__widgets_get"];
        put?: never;
        /** Create Widget */
        post: operations["create_widget_api_data_datasets__dataset_id__widgets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/datasets/{dataset_id}/widgets/{widget_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Widget */
        delete: operations["delete_widget_api_data_datasets__dataset_id__widgets__widget_id__delete"];
        options?: never;
        head?: never;
        /** Update Widget */
        patch: operations["update_widget_api_data_datasets__dataset_id__widgets__widget_id__patch"];
        trace?: never;
    };
    "/api/data/datasets/{dataset_id}/insights/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest */
        get: operations["get_latest_api_data_datasets__dataset_id__insights_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/datasets/{dataset_id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate */
        post: operations["regenerate_api_data_datasets__dataset_id__insights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Anomaly */
        Anomaly: {
            /** Id */
            id: string;
            /** Factid */
            factId: string;
            /** Column */
            column: string;
            /** At */
            at: string;
            /** Zscore */
            zScore: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "spike" | "drop";
            /** Description */
            description: string;
        };
        /** CategoricalProfile */
        CategoricalProfile: {
            /** Top */
            top: components["schemas"]["ValueCount"][];
        };
        /** ColumnProfile */
        ColumnProfile: {
            /** Nullpct */
            nullPct: number;
            /** Distinctcount */
            distinctCount: number;
            numeric?: components["schemas"]["NumericProfile"] | null;
            categorical?: components["schemas"]["CategoricalProfile"] | null;
            datetime?: components["schemas"]["DatetimeProfile"] | null;
        };
        /** ColumnTypeRequest */
        ColumnTypeRequest: {
            /**
             * Type
             * @default missing
             */
            type: unknown;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Kpis */
            kpis: components["schemas"]["Kpi"][];
            /** Widgets */
            widgets: components["schemas"]["Widget"][];
            /** Datecolumn */
            dateColumn?: string | null;
        };
        /** Dataset */
        Dataset: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Originalfilename */
            originalFilename: string;
            /**
             * Filetype
             * @enum {string}
             */
            fileType: "csv" | "xlsx";
            /** Sizebytes */
            sizeBytes: number;
            /** Rowcount */
            rowCount?: number | null;
            /** Columncount */
            columnCount?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "uploading" | "queued" | "processing" | "ready" | "failed";
            /** Errormessage */
            errorMessage?: string | null;
            /** Jobid */
            jobId?: string | null;
            /** Createdat */
            createdAt: string;
            /** Readyat */
            readyAt?: string | null;
        };
        /** DatasetColumn */
        DatasetColumn: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Originalname */
            originalName: string;
            /** Position */
            position: number;
            /**
             * Inferredtype
             * @enum {string}
             */
            inferredType: "numeric" | "categorical" | "datetime" | "boolean" | "text" | "id";
            /** Overridetype */
            overrideType?: ("numeric" | "categorical" | "datetime" | "boolean" | "text" | "id") | null;
            profile: components["schemas"]["ColumnProfile"];
        };
        /** DatasetDetail */
        DatasetDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Originalfilename */
            originalFilename: string;
            /**
             * Filetype
             * @enum {string}
             */
            fileType: "csv" | "xlsx";
            /** Sizebytes */
            sizeBytes: number;
            /** Rowcount */
            rowCount?: number | null;
            /** Columncount */
            columnCount?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "uploading" | "queued" | "processing" | "ready" | "failed";
            /** Errormessage */
            errorMessage?: string | null;
            /** Jobid */
            jobId?: string | null;
            /** Createdat */
            createdAt: string;
            /** Readyat */
            readyAt?: string | null;
            /** Columns */
            columns: components["schemas"]["DatasetColumn"][];
        };
        /** DatasetList */
        DatasetList: {
            /** Items */
            items: components["schemas"]["Dataset"][];
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /** DateRange */
        DateRange: {
            /** Column */
            column: string;
            /** From */
            from?: string | null;
            /** To */
            to?: string | null;
        };
        /** DatetimeProfile */
        DatetimeProfile: {
            /** Min */
            min: string;
            /** Max */
            max: string;
            /**
             * Grain
             * @enum {string}
             */
            grain: "hour" | "day" | "week" | "month";
        };
        /** Fact */
        Fact: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "change" | "contributor" | "anomaly" | "total";
            /** Label */
            label: string;
            /** Value */
            value: number;
            /**
             * Format
             * @enum {string}
             */
            format: "number" | "currency" | "percent" | "duration_ms" | "change";
            ref?: components["schemas"]["FactRef"] | null;
        };
        /**
         * FactRef
         * @description Where a fact lives on the dashboard, for number-to-chart highlighting.
         */
        FactRef: {
            /** Widgetid */
            widgetId: string;
            /** X */
            x: string | number;
            /** Series */
            series?: string | null;
        };
        /** FilterValuesResponse */
        FilterValuesResponse: {
            /** Column */
            column: string;
            /** Values */
            values: components["schemas"]["ValueCount"][];
        };
        /** Filters */
        Filters: {
            dateRange?: components["schemas"]["DateRange"] | null;
            /** Where */
            where?: components["schemas"]["WhereFilter"][] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
        };
        /** Insight */
        Insight: {
            /** Id */
            id: string;
            /** Datasetid */
            datasetId: string;
            /** Summary */
            summary: string;
            /** Findings */
            findings: string[];
            /** Nextquestions */
            nextQuestions: string[];
            /** Facts */
            facts: components["schemas"]["Fact"][];
            /** Anomalies */
            anomalies: components["schemas"]["Anomaly"][];
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Createdat */
            createdAt: string;
        };
        /**
         * JobDoneEvent
         * @description `event: done` payload; the stream closes after it.
         */
        JobDoneEvent: {
            /** Jobid */
            jobId: string;
            /** Datasetid */
            datasetId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "failed";
            /** Errormessage */
            errorMessage?: string | null;
        };
        /**
         * JobProgressEvent
         * @description `event: progress` payload.
         */
        JobProgressEvent: {
            /** Jobid */
            jobId: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "queued" | "parsing" | "profiling" | "building_dashboard" | "generating_insight" | "ready" | "failed";
            /** Progress */
            progress: number;
            /** Message */
            message: string;
        };
        /** Kpi */
        Kpi: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Column */
            column?: string | null;
            /**
             * Aggregation
             * @enum {string}
             */
            aggregation: "sum" | "avg" | "count" | "min" | "max" | "count_distinct";
            /** Value */
            value: number;
            /** Delta */
            delta?: number | null;
            /** Deltalabel */
            deltaLabel?: string | null;
            /**
             * Format
             * @enum {string}
             */
            format: "number" | "currency" | "percent" | "duration_ms";
        };
        /** NumericProfile */
        NumericProfile: {
            /** Min */
            min: number;
            /** Max */
            max: number;
            /** Mean */
            mean: number;
            /** Median */
            median: number;
            /** P95 */
            p95: number;
            /** Sum */
            sum: number;
        };
        /**
         * Problem
         * @description RFC 7807 error body (`application/problem+json`).
         */
        Problem: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail?: string | null;
            /** Errors */
            errors?: {
                [key: string]: string;
            } | null;
            /** Instance */
            instance?: string | null;
        };
        /** QueryRequest */
        QueryRequest: {
            /**
             * Widgets
             * @default []
             */
            widgets: components["schemas"]["QueryWidget"][];
            /**
             * Kpis
             * @default false
             */
            kpis: boolean;
            /** @default {} */
            filters: components["schemas"]["Filters"];
        };
        /** QueryResponse */
        QueryResponse: {
            /** Kpis */
            kpis: components["schemas"]["Kpi"][];
            /** Results */
            results: components["schemas"]["WidgetResult"][];
        };
        /** QueryWidget */
        QueryWidget: {
            /** Id */
            id: string;
            spec: components["schemas"]["WidgetSpec"];
        };
        /** RegenerateInsightResponse */
        RegenerateInsightResponse: {
            /** Jobid */
            jobId: string;
        };
        /** RowsResponse */
        RowsResponse: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: {
                [key: string]: boolean | number | string | null;
            }[];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** SampleRequest */
        SampleRequest: {
            /** Key */
            key?: string | null;
        };
        /**
         * SeriesPoint
         * @description One point: `x` plus one number per series, so extra keys are expected.
         */
        SeriesPoint: {
            /** X */
            x: string | number;
            /** X2 */
            x2?: number | null;
        } & {
            [key: string]: number;
        };
        /** UploadResponse */
        UploadResponse: {
            dataset: components["schemas"]["Dataset"];
            /** Jobid */
            jobId: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValueCount */
        ValueCount: {
            /** Value */
            value: string;
            /** Count */
            count: number;
        };
        /** WhereFilter */
        WhereFilter: {
            /** Column */
            column: string;
            /**
             * Op
             * @default in
             * @constant
             */
            op: "in";
            /** Values */
            values: string[];
        };
        /** Widget */
        Widget: {
            /** Id */
            id: string;
            /** Datasetid */
            datasetId: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "auto" | "custom";
            spec: components["schemas"]["WidgetSpec"];
            /** Position */
            position: number;
            /** Createdat */
            createdAt: string;
        };
        /**
         * WidgetRequest
         * @description Chart create/update body. The spec stays loose so `validate_spec` can
         *     answer with the contract's field messages instead of FastAPI's.
         */
        WidgetRequest: {
            /** Spec */
            spec?: {
                [key: string]: unknown;
            } | null;
        };
        /** WidgetResult */
        WidgetResult: {
            /** Widgetid */
            widgetId: string;
            /** Series */
            series: string[];
            /** Points */
            points: components["schemas"]["SeriesPoint"][];
            /**
             * Format
             * @enum {string}
             */
            format: "number" | "currency" | "percent" | "duration_ms" | "change";
            /** Xformat */
            xFormat?: ("number" | "currency" | "percent" | "duration_ms" | "change") | null;
        };
        /** WidgetSpec */
        WidgetSpec: {
            /**
             * Charttype
             * @enum {string}
             */
            chartType: "line" | "area" | "bar" | "donut" | "histogram";
            /** Title */
            title: string;
            /** X */
            x: string;
            /** Y */
            y?: string | null;
            /**
             * Aggregation
             * @enum {string}
             */
            aggregation: "sum" | "avg" | "count" | "min" | "max" | "count_distinct";
            /** Split */
            split?: string | null;
            /** Timegrain */
            timeGrain?: ("hour" | "day" | "week" | "month") | null;
            /** Limit */
            limit?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_data_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_datasets_api_data_datasets_get: {
        parameters: {
            query?: {
                q?: string;
                sort?: string;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dataset_api_data_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unsupported file type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_sample_api_data_datasets_sample_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_dataset_api_data_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_api_data_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_column_type_api_data_datasets__dataset_id__columns__column_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                column_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColumnTypeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetColumn"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    job_events_api_data_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `progress` events until a final `done` event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["JobProgressEvent"] | components["schemas"]["JobDoneEvent"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_data_datasets__dataset_id__dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_api_data_datasets__dataset_id__query_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    rows_api_data_datasets__dataset_id__rows_get: {
        parameters: {
            query?: {
                page?: string;
                pageSize?: string;
                sort?: string;
                filters?: string | null;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowsResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filter_values_api_data_datasets__dataset_id__filters__column__values_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path: {
                dataset_id: string;
                column: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterValuesResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_widgets_api_data_datasets__dataset_id__widgets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Widget"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_widget_api_data_datasets__dataset_id__widgets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WidgetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Widget"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_widget_api_data_datasets__dataset_id__widgets__widget_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                widget_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_widget_api_data_datasets__dataset_id__widgets__widget_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                widget_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WidgetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Widget"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_latest_api_data_datasets__dataset_id__insights_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Insight"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_api_data_datasets__dataset_id__insights_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegenerateInsightResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
